Repository milieuinfo/webcomponent-vl-ui-toaster, pull requests merged in 2019-09, with the labels that each got.

#11 UIG-218
  vl-toaster.src.js
Labels: maintenance

#12 Update link naar demo
  vl-toaster.src.js
Labels: maintenance

#14 Automatic commit via update script
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  package-lock.json
  package.json
Labels: maintenance

#2 Update dependency np to v3.1.0
  package-lock.json
  package.json
Labels: renovate

#21 Update dependency vl-ui-core to v1.4.6
  package-lock.json
  package.json
Labels: dependencies

#20 Update dependency vl-ui-button to v1.1.9
  package-lock.json
  package.json
Labels: dependencies

#19 Update dependency replace to v1.1.1
  package-lock.json
  package.json
Labels: dependencies

#18 Update dependency @govflanders/vl-ui-util to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#17 Update dependency @govflanders/vl-ui-icon to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#16 Update dependency @govflanders/vl-ui-core to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#15 Update dependency @govflanders/vl-ui-button to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#22 Update dependency vl-ui-core to v1.4.7
  package-lock.json
  package.json
Labels: dependencies

#27 Automatic commit via update script
  demo/demo.css
  package-lock.json
  style.css
Labels: maintenance

#29 Update and install latest util
  .github/ISSUE_TEMPLATE/task.md
  bamboo-specs/bamboo.yml
  demo/demo.css
  package-lock.json
  package.json
  style.css
Labels: maintenance

#35 Update dependency vl-ui-button to v1.1.12
  package-lock.json
  package.json
Labels: dependencies
