Repository milieuinfo/webcomponent-vl-ui-toaster, pull requests merged in 2020-01, with the labels that each got.

#52 Update vl-ui-util
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.js
  package-lock.json
  package.json
  style.css
  test/docker-compose.yml
  wct.docker.conf.json
  wct.local.conf.json
Labels: maintenance

#53 Bugfix: de toaster.js is niet opgeladen in online demo pagina
  .mocharc.js
  demo/demo.css
  index.js
  package-lock.json
  package.json
  style.css
  test/e2e/components/vl-toaster.js
  test/e2e/pages/vl-toaster.page.js
  test/e2e/toaster.test.js
  test/unit/docker-compose.yml
  test/unit/vl-toaster.test.html
  test/wct.docker.conf.json
  vl-toaster.src.js
Labels: bugfix

#54 Overbodig NPM release import scripts verwijderd
  package.json
Labels: maintenance

#56 Verwijder pretest fase (installeren chromedriver). Deze komt via vl-ui-util binnen
  package.json
Labels: chore

#55 Update vl-ui-util
  demo/demo.css
  package-lock.json
  package.json
  style.css
  test/docker-compose.yml
Labels: maintenance

#57 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance

#58 Update vl-ui-util
  bamboo-specs/bamboo.yml
  docker-compose-release.yml
  package-lock.json
  package.json
Labels: maintenance
