Repository milieuinfo/webcomponent-vl-ui-toaster, pull requests merged in 2020-03, with the labels that each got.

#65 Upate vl-ui-util voor ondersteuning double en single quotes imports
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  package-lock.json
  package.json
Labels: bug

#66 Update vl-ui-util
  package-lock.json
  package.json
Labels: chore, maintenance

#67 Update vl-ui-core
  package-lock.json
  package.json
Labels: chore

#68 Update vl-ui-core
  package-lock.json
  package.json
Labels: chore
